import os
print("###################################################################")
print("Deleting Database")
os.system("rm -rf db.sqlite3")
print("###################################################################")
print("Deleting Migrations Folder...")
os.system("rm -rf accounts/migrations/")
print("Rebuilding the Migrations...")
os.system("python manage.py makemigrations accounts")
print("Rebuilding the database...")
os.system("python manage.py migrate")
print("###################################################################")
print("Create a Super User")
os.system("python manage.py createsuperuser")
print("@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@")
print("Running Server")
os.system("python manage.py runserver")

