# Generated by Django 2.0.1 on 2018-06-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(null=True),
        ),
    ]
