# Generated by Django 2.0.6 on 2018-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='solution_link',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
