# Generated by Django 2.0.1 on 2018-06-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='people_interested',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
