# Generated by Django 2.0.1 on 2018-06-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_projectdetail_people_interested'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdetail',
            name='initiated_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
