# Generated by Django 2.0.1 on 2018-06-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180612_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ratings',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
