# Generated by Django 2.0 on 2018-05-29 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180529_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectdetail',
            name='duration',
        ),
        migrations.AddField(
            model_name='projectdetail',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='description',
            field=models.CharField(max_length=2500),
        ),
    ]
