# Generated by Django 2.0.6 on 2018-06-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Skill'),
        ),
        migrations.AlterField(
            model_name='projectdetail',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.CharField(blank=True, default='Not Updated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, default='Not Updated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='position',
            field=models.CharField(blank=True, default='Not Updated', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='stream',
            field=models.CharField(blank=True, default='Not Updated', max_length=20, null=True),
        ),
    ]
