# Generated by Django 2.0.6 on 2018-06-23 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180621_0131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPeopleInterested',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectdetail',
            name='people_interested',
        ),
        migrations.AddField(
            model_name='projectpeopleinterested',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='accounts.ProjectDetail'),
        ),
        migrations.AddField(
            model_name='projectpeopleinterested',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
