# Generated by Django 2.0.6 on 2018-06-27 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180626_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetail',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.Skill'),
        ),
    ]
