# Generated by Django 2.0.2 on 2018-02-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180219_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tools',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tools',
            field=models.ManyToManyField(to='accounts.Tool'),
        ),
    ]
