# Generated by Django 2.0.2 on 2018-02-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180220_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, to='accounts.Book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, to='accounts.Skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tools',
            field=models.ManyToManyField(blank=True, to='accounts.Tool'),
        ),
    ]
