# Generated by Django 2.0.2 on 2018-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180220_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='books',
            field=models.ManyToManyField(blank=True, default='', to='accounts.Book'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skill',
            field=models.ManyToManyField(blank=True, default='', to='accounts.Skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tools',
            field=models.ManyToManyField(blank=True, default='', to='accounts.Tool'),
        ),
    ]
