# Generated by Django 2.0.2 on 2018-03-03 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180220_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='books',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tools',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
    ]
