# Generated by Django 2.0.6 on 2018-07-07 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20180705_0355'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Follow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestedNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ProjectDetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('issueComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.IssueComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('solutionComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SolutionComment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolutionNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], max_length=1)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
