# Generated by Django 2.0.6 on 2018-07-08 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('redirect', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('1', 'Seen'), ('0', 'Unseen')], default='0', max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='follownotification',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='follownotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='interestednotification',
            name='project',
        ),
        migrations.RemoveField(
            model_name='interestednotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issuecommentnotification',
            name='issueComment',
        ),
        migrations.RemoveField(
            model_name='issuecommentnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='issuenotification',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuenotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solutioncommentnotification',
            name='solutionComment',
        ),
        migrations.RemoveField(
            model_name='solutioncommentnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='solutionnotification',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionnotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='FollowNotification',
        ),
        migrations.DeleteModel(
            name='InterestedNotification',
        ),
        migrations.DeleteModel(
            name='IssueCommentNotification',
        ),
        migrations.DeleteModel(
            name='IssueNotification',
        ),
        migrations.DeleteModel(
            name='SolutionCommentNotification',
        ),
        migrations.DeleteModel(
            name='SolutionNotification',
        ),
    ]
